[package]
name = "loyalfier_test"
version = "0.1.0"
edition = "2021"

[dependencies]
libloyalfier = { path = "../libloyalfier" }
photon-rs = { git = "https://github.com/silvia-odwyer/photon.git", default-features = false }
rand = "0.8.5"
